= README
Bastian Basler
:description: Projektbeschreibung
:url-repo: https://github.com/babasler/training-recording-device

== Vision
Das Projekt soll ein System zur Aufzeichnung und Visualisierung des Trainingsfortschritts und des körperlichen Zustandes eines Benutzers ergeben. Dabei soll das System diverse Daten aufzeichnen, verarbeiten, speichern und dem Benutzer in einer übersichtlichen Form präsentieren. Es sollen Sätze, Wiederholungen, das Volumen, der Puls, den Sauerstoffgehalt im Blut, die Schritte über den Tag und das Körpergewicht aufgezeichnet werden. Dabei soll der Fokus auf dem Krafttraining und Zirkeltraining liegen. Der Benutzer soll die Möglichkeit haben, vorgegebene Trainingspläne zu verfolgen, oder eigene Trainingspläne zu erstellen, das umfasst auch einen Splitfootnote:[Expose in /arc42/arc42.adoc] und eine Trainingsfrequenz sowie die Möglichkeit, Sportarten zu kombinieren. Zum Beispiel einen Kraft- und einen HIIT Teil in einem Workout. Die Trainingspläne sollen aus vorgefertigten oder aus selbst erstellten Übungen erstellt werden können. Der Benutzer soll seine bevorzugte Pausenzeit einstellen, damit diese während des Trainings dargestellt werden kann. Im Falle von Zirkeltraining soll eine Belastung und eine Pausenzeit eingestellt werden können. Der Benutzer soll einmal in der Woche eine Übersicht über seinen Trainingsfortschritt erhalten und gegebenenfalls eine Erinnerung über versäumte Trainings erhalten. Um mehrere Benutzer zu ermöglichen, soll das System eine Möglichkeit bieten, sich zu authentifizieren, damit die richtigen Daten der richtigen Person zugeordnet werden können.

== Visualisierung




