# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the application's JAR file to the container
COPY target/*.jar app.jar

# Expose the port the app runs on
EXPOSE 8084

# Run the JAR file
ENTRYPOINT ["java", "-jar", "app.jar"]