name: Deploy on Raspberry Pi

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: [self-hosted, ARM64, Linux]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Stop Docker Container
        run: |
          cd code/test
          docker compose down
      - name: Install Dependencies and build Frontend
        run: |
          pwd
          cd code/test/frontend
          npm install
          npm run build --prod
      - name: Build Backend
        run: |
          cd code/test/backend
          mvn clean package
      - name: Start Docker Container
        run: |
          cd code/test
          docker compose build
          docker compose up -d 
          
