name: Deploy on Raspberry Pi

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: [self-hosted, ARM64, Linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy on Rasberry Pi
        run: |
          cd code/test/
          docker compose down
          cd backend/
          mvn clean package
          cd ..
          docker compose build --no-cache
          docker compose up -d 
          
