name: Deploy on Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, ARM64, Linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Stop Docker Container
        run: |
          cd code/test/
          docker compose down
          cd backend/
          mvn clean package
          cd ..
          cd frontend/
          npm install
          ng build --configuration=production
          docker compose up --build -d
